/ros_param/rate: 200

/t_motor/n_drives: 1

# Motor setting parameters

# Motor types
# 1. AK70_10 : 0
# 2. AK80_64 : 1

# Drive modes
# 1. SERVO_MODE : 0
# 2. MIT_MODE : 1

/t_motor/motor/drive_ids: [1]
/t_motor/motor/motor_types: [1]
/t_motor/motor/drive_modes: [1]

# Motor control parameters

/t_motor/control/reference_pos: [0]
/t_motor/control/reference_speed: [0]

/t_motor/control/kp: [100]
/t_motor/control/kd: [0]

/t_motor/control/torquePD_flag: 2
